export default function PDFExport({ report }) {
  const handlePrint = () => {
    const printContent = `
      <html>
        <head>
          <title>FixMyCampus Report - ${report.title}</title>
          <style>
            body { font-family: Arial, sans-serif; padding: 2rem; color: #333; }
            h1 { color: #e94560; border-bottom: 2px solid #e94560; padding-bottom: 0.5rem; }
            .badge { display: inline-block; padding: 0.25rem 0.75rem; border-radius: 20px; font-size: 0.85rem; font-weight: 600; margin-right: 0.5rem; }
            .grid { display: grid; grid-template-columns: 1fr 1fr; gap: 1rem; margin: 1rem 0; }
            .field { margin-bottom: 1rem; }
            .label { font-size: 0.85rem; color: #666; margin-bottom: 0.25rem; }
            .value { font-weight: 600; }
            .description { background: #f8f9fa; padding: 1rem; border-radius: 8px; line-height: 1.6; }
            .comment { background: #f0f0f0; padding: 0.75rem; border-radius: 8px; margin-bottom: 0.5rem; }
            .footer { margin-top: 2rem; font-size: 0.8rem; color: #999; border-top: 1px solid #eee; padding-top: 1rem; }
          </style>
        </head>
        <body>
          <h1>FixMyCampus Maintenance Report</h1>
          <h2>${report.title}</h2>
          <div>
            <span class="badge" style="background:#dbeafe;color:#1d4ed8">${report.status}</span>
            <span class="badge" style="background:#fef3c7;color:#92400e">${report.priority}</span>
            <span class="badge" style="background:#f3f4f6;color:#374151">${report.category}</span>
          </div>
          <div class="grid">
            <div class="field"><div class="label">Building</div><div class="value">${report.building}</div></div>
            <div class="field"><div class="label">Location</div><div class="value">${report.location}</div></div>
            <div class="field"><div class="label">Reported By</div><div class="value">${report.reportedBy}</div></div>
            <div class="field"><div class="label">Date Submitted</div><div class="value">${new Date(report.createdAt).toLocaleDateString()}</div></div>
          </div>
          <div class="field">
            <div class="label">Description</div>
            <div class="description">${report.description}</div>
          </div>
          ${report.comments?.length > 0 ? `
            <h3>Comments (${report.comments.length})</h3>
            ${report.comments.map(c => `
              <div class="comment">
                <strong>${c.addedBy}</strong> - ${new Date(c.addedAt).toLocaleString()}<br/>
                ${c.text}
              </div>
            `).join('')}
          ` : ''}
          <div class="footer">
            Generated by FixMyCampus on ${new Date().toLocaleString()} | Report ID: ${report._id}
          </div>
        </body>
      </html>
    `;
    const printWindow = window.open('', '_blank');
    printWindow.document.write(printContent);
    printWindow.document.close();
    printWindow.print();
  };

  return (
    <button className="btn btn-success" onClick={handlePrint} style={{ marginLeft:'0.5rem' }}>
      📄 Export PDF
    </button>
  );
}